### ISSUE TITLE
Segfaults after multiple configuration reloads

### ISSUE THREAD

**Issue by pyh** [vkholodkov/nginx-mogilefs-module#1]
Nginx will segfault on every mogilefs request after configuration has been reloaded 6 times with "kill -HUP"

This is simplified configuration that triggers the segfault condition:

<pre>
user www-data;

pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    server {
        listen       12345;

        location /testdomain.com/files/ {
            mogilefs_tracker 127.0.0.1:47075;
            mogilefs_domain testdomain.com;
            mogilefs_methods GET PUT DELETE;
            mogilefs_class files;

            mogilefs_pass {
               proxy_pass $mogilefs_path;
               proxy_hide_header Content-Type;
               proxy_buffering off;
           }
        }
    }
}
</pre>

If I add in another mogilefs block:

<pre>
        location /testdomain2.com/files2/ {
            mogilefs_tracker 127.0.0.1:47075;
            mogilefs_domain testdomain2.com;
            mogilefs_methods GET PUT DELETE;
            mogilefs_class files2;

            mogilefs_pass {
               proxy_pass $mogilefs_path;
               proxy_hide_header Content-Type;
               proxy_buffering off;
           }
        }
</pre>

Then only 3 reloads are needed to start the segfaulting. I used nginx-mogilefs-module master from github and nginx-0.7.67. Complied and ran the tests on ubuntu 10.04, but same issue is happening on our production servers that use Debian Lenny.

configure arguments:

<pre>
./configure --with-http_stub_status_module --with-http_ssl_module --conf-path=/usr/local/etc/nginx.conf --error-log-path=/var/log/nginx/error_log --http-log-path=/var/log/nginx/access_log --sbin-path=/usr/local/sbin/nginx --with-http_dav_module --add-module=../nginx-mogilefs-module
</pre>

You can trigger the error with following:

<pre>
/usr/local/sbin/nginx
kill -HUP `cat /var/run/nginx.pid`
kill -HUP `cat /var/run/nginx.pid`
kill -HUP `cat /var/run/nginx.pid`
kill -HUP `cat /var/run/nginx.pid`
kill -HUP `cat /var/run/nginx.pid`
kill -HUP `cat /var/run/nginx.pid`
curl -I http://localhost:12345/testdomain.com/files/1.jpg
</pre>

Working mogilefs installation is not needed to trigger the issue, it happens before connecting to mogilefs.

**Comment by vkholodkov** [comment]
I have problems reproducing your issue. Here is what I get:

# curl -I http://localhost:80/testdomain.com/files/1.jpg

HTTP/1.1 500 Internal Server Error
Server: nginx/0.7.67
Date: Mon, 16 Aug 2010 09:34:16 GMT
Content-Type: text/html
Content-Length: 193
Connection: close

Could you send a backtrace of the core and/or debug log please?

**Comment by pyh** [comment]
backtrace:

<pre>
Program received signal SIGSEGV, Segmentation fault.
0x000000000045be9d in ngx_http_mogilefs_eval_class (r=0xfa9460) at ../nginx-mogilefs-module/ngx_http_mogilefs_module.c:645
645                 if(ngx_http_script_run(r, &class, t-&gt;lengths-&gt;elts, 0,
(gdb) bt
#0  0x000000000045be9d in ngx_http_mogilefs_eval_class (r=0xfa9460) at ../nginx-mogilefs-module/ngx_http_mogilefs_module.c:645
#1  ngx_http_mogilefs_create_request (r=0xfa9460) at ../nginx-mogilefs-module/ngx_http_mogilefs_module.c:786
#2  0x000000000043b6ae in ngx_http_upstream_init (r=0xfa9460) at src/http/ngx_http_upstream.c:451
#3  0x000000000045b5e9 in ngx_http_mogilefs_handler (r=0xfa9460) at ../nginx-mogilefs-module/ngx_http_mogilefs_module.c:379
#4  0x000000000042913b in ngx_http_core_content_phase (r=0xfa9460, ph=0xfbd388) at src/http/ngx_http_core_module.c:1279
#5  0x0000000000425773 in ngx_http_core_run_phases (r=0xfa9460) at src/http/ngx_http_core_module.c:817
#6  0x00000000004258ac in ngx_http_handler (r=0xfa9460) at src/http/ngx_http_core_module.c:800
#7  0x000000000042e381 in ngx_http_process_request (r=0xfa9460) at src/http/ngx_http_request.c:1636
#8  0x000000000042e947 in ngx_http_process_request_headers (rev=&lt;value optimized out&gt;) at src/http/ngx_http_request.c:1079
#9  0x000000000042ee51 in ngx_http_process_request_line (rev=0xfbfed0) at src/http/ngx_http_request.c:884
#10 0x000000000042c5d8 in ngx_http_init_request (rev=0xfbfed0) at src/http/ngx_http_request.c:510
#11 0x000000000041fb37 in ngx_epoll_process_events (cycle=&lt;value optimized out&gt;, timer=&lt;value optimized out&gt;, flags=&lt;value optimized out&gt;)
    at src/event/modules/ngx_epoll_module.c:518
#12 0x0000000000418b7f in ngx_process_events_and_timers (cycle=0xf8b030) at src/event/ngx_event.c:245
#13 0x000000000041e808 in ngx_worker_process_cycle (cycle=0xf8b030, data=&lt;value optimized out&gt;) at src/os/unix/ngx_process_cycle.c:791
#14 0x000000000041d02c in ngx_spawn_process (cycle=0xf8b030, proc=0x41e73b &lt;ngx_worker_process_cycle&gt;, data=&lt;value optimized out&gt;,
    name=0x4603c1 "worker process", respawn=0) at src/os/unix/ngx_process.c:194
#15 0x000000000041efae in ngx_reap_children (cycle=0xf8b030) at src/os/unix/ngx_process_cycle.c:612
#16 ngx_master_process_cycle (cycle=0xf8b030) at src/os/unix/ngx_process_cycle.c:180
#17 0x00000000004067e4 in main (argc=&lt;value optimized out&gt;, argv=&lt;value optimized out&gt;) at src/core/nginx.c:396
(gdb) p r
$1 = &lt;value optimized out&gt;
(gdb) p class
$2 = {len = 140736227043896, data = 0x7f74532aa128 ""}
(gdb) p t
$3 = (ngx_http_mogilefs_class_template_t *) 0xf9f818
(gdb) p t-&gt;lengths-&gt;elts
$4 = (void *) 0x696c412d7065654b
(gdb) p t-&gt;values-&gt;elts
Cannot access memory at address 0x0
</pre>

Debug log only contains one request, the one that segfaults. I can send the full log via email if needed.

<pre>
2010/08/16 15:59:09 [debug] 11504#0: epoll: fd:6 ev:0001 d:00007FB5512DA010
2010/08/16 15:59:09 [debug] 11504#0: accept on 0.0.0.0:12345, ready: 0
2010/08/16 15:59:09 [debug] 11504#0: malloc: 0000000001E56EF0:256
2010/08/16 15:59:09 [debug] 11504#0: *18 accept: 127.0.0.1 fd:3
2010/08/16 15:59:09 [debug] 11504#0: *18 event timer add: 3: 60000:1281963609577
2010/08/16 15:59:09 [debug] 11504#0: *18 epoll add event: fd:3 op:1 ev:80000001
2010/08/16 15:59:09 [debug] 11504#0: timer delta: 4183
2010/08/16 15:59:09 [debug] 11504#0: posted events 0000000000000000
2010/08/16 15:59:09 [debug] 11504#0: worker cycle
2010/08/16 15:59:09 [debug] 11504#0: epoll timer: 60000
2010/08/16 15:59:09 [debug] 11504#0: epoll: fd:3 ev:0001 d:00007FB5512DA180
2010/08/16 15:59:09 [debug] 11504#0: *18 malloc: 0000000001E3AF70:1280
2010/08/16 15:59:09 [debug] 11504#0: *18 malloc: 0000000001E570F0:256
2010/08/16 15:59:09 [debug] 11504#0: *18 malloc: 0000000001E3B480:1024
2010/08/16 15:59:09 [debug] 11504#0: *18 malloc: 0000000001E34760:4096
2010/08/16 15:59:09 [debug] 11504#0: *18 http process request line
2010/08/16 15:59:09 [debug] 11504#0: *18 recv: fd:3 183 of 1024
2010/08/16 15:59:09 [debug] 11504#0: *18 http request line: "HEAD /testdomain.com/files/1.jpg HTTP/1.1"
2010/08/16 15:59:09 [debug] 11504#0: *18 http uri: "/testdomain.com/files/1.jpg"
2010/08/16 15:59:09 [debug] 11504#0: *18 http args: ""
2010/08/16 15:59:09 [debug] 11504#0: *18 http exten: "jpg"
2010/08/16 15:59:09 [debug] 11504#0: *18 http process request header line
2010/08/16 15:59:09 [debug] 11504#0: *18 http header: "User-Agent: curl/7.19.7 (x86_64-pc-linux-gnu) libcurl/7.19.7 OpenSSL/0.9.8k zlib/1.2.3.3 libidn/1.15"
2010/08/16 15:59:09 [debug] 11504#0: *18 http header: "Host: localhost:12345"
2010/08/16 15:59:09 [debug] 11504#0: *18 http header: "Accept: */*"
2010/08/16 15:59:09 [debug] 11504#0: *18 http header done
2010/08/16 15:59:09 [debug] 11504#0: *18 event timer del: 3: 1281963609577
2010/08/16 15:59:09 [debug] 11504#0: *18 generic phase: 0
2010/08/16 15:59:09 [debug] 11504#0: *18 test location: "/mogstored_spare_31851712/"
2010/08/16 15:59:09 [debug] 11504#0: *18 test location: "/testdomain.com/files/"
2010/08/16 15:59:09 [debug] 11504#0: *18 using configuration "/testdomain.com/files/"
2010/08/16 15:59:09 [debug] 11504#0: *18 http cl:-1 max:1048576
2010/08/16 15:59:09 [debug] 11504#0: *18 generic phase: 2
2010/08/16 15:59:09 [debug] 11504#0: *18 post rewrite phase: 3
2010/08/16 15:59:09 [debug] 11504#0: *18 generic phase: 4
2010/08/16 15:59:09 [debug] 11504#0: *18 generic phase: 5
2010/08/16 15:59:09 [debug] 11504#0: *18 access phase: 6
2010/08/16 15:59:09 [debug] 11504#0: *18 access phase: 7
2010/08/16 15:59:09 [debug] 11504#0: *18 post access phase: 8
2010/08/16 15:59:09 [debug] 11504#0: *18 http init upstream, client timer: 0
2010/08/16 15:59:09 [debug] 11504#0: *18 epoll add event: fd:3 op:3 ev:80000005
2010/08/16 15:59:09 [notice] 11457#0: signal 17 (SIGCHLD) received
2010/08/16 15:59:09 [alert] 11457#0: worker process 11504 exited on signal 11
2010/08/16 15:59:09 [debug] 11457#0: wake up, sigio 0
2010/08/16 15:59:09 [debug] 11457#0: reap children
2010/08/16 15:59:09 [debug] 11457#0: child: 0 -1 e:1 t:1 d:0 r:1 j:0
2010/08/16 15:59:09 [debug] 11457#0: child: 1 11504 e:0 t:1 d:0 r:1 j:0
2010/08/16 15:59:09 [debug] 11457#0: channel 3:7
2010/08/16 15:59:09 [notice] 11457#0: start worker process 11507
2010/08/16 15:59:09 [debug] 11457#0: sigsuspend
2010/08/16 15:59:09 [debug] 11507#0: malloc: 0000000001E32F50:6144
2010/08/16 15:59:09 [debug] 11507#0: malloc: 00007FB5512DA010:188416
2010/08/16 15:59:09 [debug] 11507#0: malloc: 0000000001E675F0:106496
2010/08/16 15:59:09 [debug] 11507#0: malloc: 0000000001E81600:106496
2010/08/16 15:59:09 [debug] 11507#0: epoll add event: fd:6 op:1 ev:00000001
2010/08/16 15:59:09 [debug] 11507#0: epoll add event: fd:7 op:1 ev:00000001
2010/08/16 15:59:09 [debug] 11507#0: setproctitle: "nginx: worker process"
2010/08/16 15:59:09 [debug] 11507#0: worker cycle
2010/08/16 15:59:09 [debug] 11507#0: epoll timer: -1
</pre>

I also compiled nginx-0.8.49 and verified that the issue is there also, but on 0.8.49 it requires 9 reloads before segfaults start.

I used this to test if the configuration segfaults, so far everything does:

<pre>
for i in `seq 1 100`
do
    echo -n "Reload $i "
    kill -HUP `cat /var/run/nginx.pid`
    if [ $(curl -sI localhost:12345/testdomain.com/files/1.jpg|grep -c Server) -ne 0 ]; then
        echo ok
    else
        echo fail
    fi
done
</pre>

**Comment by vkholodkov** [comment]
Please try following patch:
http://github.com/vkholodkov/nginx-mogilefs-module/commit/6f5999b6baed17403442e64fbbf1fe7ab5113410

**Comment by pyh** [comment]
Seems to be working perfectly. Thank you!
